import Head from "next/head";

import { Header } from "@/components/header";
import { ButtonRedirectToLetterOfAttorney } from "@/components/ButtonRedirectToLetterOfAttorney";

export default function Home() {
  return (
    <>
      <Head>
        <title>Quid</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header isHomePage />
      <div className="h-screen overflow-hidden bg-[url('/assets/bg-img.svg')] bg-contain bg-no-repeat bg-right-bottom">
        <main className="max-w-[1440px] mt-72 ml-32 text-text-500">
          <h1 className="text-5xl text-bold font-bold pb-11">
            Somos facilitadores de <br /> processos jurídicos.
          </h1>

          <p className="text-lg pb-11">
            Lorem ipsum is placeholder text commonly used in the graphic,
            <br /> print, and publishing industries for previewing layouts and
            visual mockups.
          </p>

          <div className="max-w-[547px] flex items-center justify-start">
            <ButtonRedirectToLetterOfAttorney text="Experimente já!" />
            <span className="text-lg ml-10">Tem dúvidas? Nós ajudamos.</span>
          </div>
        </main>
      </div>
    </>
  );
}
